name: Faraway
version: '${version}'
main: io.github.sharkzhs83.faraway.Faraway
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.10
  - io.github.monun:tap-core:4.9.8
  - io.github.monun:invfx-core:3.3.2
  - io.github.monun:kommand-core:3.1.7